//
//  ChemicalsTableViewController.swift
//  Ashland-Nyanza Project
//
//  Created by Lorraine Fryer on 9/8/15.
//  Copyright (c) 2015 Lorraine Fryer. All rights reserved.
//

import UIKit

class ChemicalsTableViewController: UITableViewController {

    @IBAction func back(sender: UIButton) {
        dismissViewControllerAnimated(true, completion: nil)
    }

    
    var chemicalsList = [ChemicalsListItem]()
    override func viewDidLoad() {
        super.viewDidLoad()
        loadChemicalsList()

        // Uncomment the following line to preserve selection between presentations
        // self.clearsSelectionOnViewWillAppear = false

        // Uncomment the following line to display an Edit button in the navigation bar for this view controller.
        // self.navigationItem.rightBarButtonItem = self.editButtonItem()
    }
    
    func loadChemicalsList() {
        
        let photo1 = UIImage(named: "acenaphthylene.png")!
        let chem1 = ChemicalsListItem(text: "Acenaphthylene", photo: photo1, descrip: "Acenaphthylene is one of a group of polycyclic aromatic hydrocarbons (PAHs). PAHs are a group of chemicals that are formed during the incomplete burning of coal, oil, gas, wood, garbage, or other organic substances, such as tobacco and charbroiled meat. There are more than 100 different PAHs. PAHs usually occur naturally, but they can be manufactured as individual compounds for research purposes. PAHs can be harmful to your health under some circumstances. Studies of people show that individuals exposed by breathing or skin contact for long periods to mixtures that contain PAHs and other compounds can develop cancer.")
        
        let photo2 = UIImage(named: "acetone.png")!
        let chem2 = ChemicalsListItem(text: "Acetone", photo: photo2, descrip: "Acetone is a chemical that is found naturally in the environment and is also produced by industries. Most acetone produced is used to make other chemicals that make plastics, fibers, and drugs. Acetone is also used to dissolve other substances. Most people can smell acetone in the air at 100 to 140 ppm; that means you will probably smell acetone before you feel effects like headache and confusion. Levels of acetone in air in rural areas and in cities (less than 8 ppb) are generally lower than this.")
        
        let photo3 = UIImage(named: "aldrin.png")!
        let chem3 = ChemicalsListItem(text: "Aldrin", photo: photo3, descrip: "Aldrin and dieldrin are the common names of two structurally similar compounds that were once used as insecticides. They are chemicals that are made in the laboratory and do not occur naturally in the environment.  The two chemicals are discussed together because aldrin readily changes into dieldrin once it enters either the environment or your body. From the 1950s until 1970, aldrin and dieldrin entered the environment when farmers used these compounds to kill pests on crops and when exterminators used them to kill termites. Aldrin and dieldrin are still present in the environment from these past uses. Symptoms of aldrin and dieldrin poisoning have been seen in people who were exposed to very large amounts of these pesticides during their manufacture. Most of these people experienced convulsions or other nervous system effects, and some had kidney damage. Health effects in people exposed to smaller amounts of aldrin or dieldrin occur because levels of the chemicals build up in the body over time. Exposure to moderate levels of aldrin or dieldrin for a long time causes headaches, dizziness, irritability, vomiting, or uncontrollable muscle movements. We do not know whether aldrin or dieldrin affects the ability of people to fight diseases, or causes birth defects or cancer in people.")
        
        let photo4 = UIImage(named: "aniline.png")!
        let chem4 = ChemicalsListItem(text: "Aniline", photo: photo4, descrip: "Aniline is used to make a wide variety of products such as polyurethane foam, agricultural chemicals, synthetic dyes, antioxidants, stabilizers for the rubber industry, herbicides, varnishes and explosives.  If you work in a place that makes products like dyes, varnishes, herbicides, and explosives, you may be exposed to aniline. People living near uncontrolled hazardous waste sites may be exposed to higher than normal levels of aniline. Aniline has also been detected in tobacco smoke, so people who smoke or breath in second-hand smoke may also be exposed to aniline. Rats that ate food contaminated with aniline for life developed cancer of the spleen. Children should avoid playing in soils near uncontrolled hazardous waste sites where aniline may have been discarded. ")
        
        let photo5 = UIImage(named: "antimony.png")!
        let chem5 = ChemicalsListItem(text: "Antimony", photo: photo5, descrip: "Antimony isn't used alone because it breaks easily, but when mixed into alloys, it is used in lead storage batteries, solder, sheet and pipe metal, bearings, castings, and pewter. Antimony oxide is added to textiles and plastics to prevent them from catching fire. In polluted areas containing high levels of antimony, it may be found in the air, water, and soil. Exposure to antimony at high levels can result in a variety of adverse health effects. Breathing high levels for a long time can irritate your eyes and lungs and can cause heart and lung problems, stomach pain, diarrhea, vomiting, and stomach ulcers. We don't know whether antimony will cause cancer in people. Antimony can have beneficial effects when used for medical reasons. It has been used as a medicine to treat people infected with parasites.")
        
        let photo6 = UIImage(named: "arsenic.png")!
        let chem6 = ChemicalsListItem(text: "Arsenic", photo: photo6, descrip: "Arsenic is a naturally occurring element widely distributed in the earth’s crust. Organic arsenic compounds are used as pesticides, primarily on cotton fields and orchards. Inorganic arsenic compounds are mainly used to preserve wood. Several studies have shown that ingestion of inorganic arsenic can increase the risk of skin cancer and cancer in the liver, bladder, and lungs. Inhalation of inorganic arsenic can cause increased risk of lung cancer. There is some evidence that long-term exposure to arsenic in children may result in lower IQ scores. There is also some evidence that exposure to arsenic in the womb and early childhood may increase mortality in young adults. There is some evidence that inhaled or ingested arsenic can injure pregnant women or their unborn babies, although the studies are not definitive.")
        
        let photo7 = UIImage(named: "barium.png")!
        let chem7 = ChemicalsListItem(text: "Barium", photo: photo7, descrip: "Barium compounds are used by the oil and gas industries to make it easier to drill through rock by keeping the drill bit lubricated. They are also used to make paint, bricks, ceramics, glass, and rubber. The health effects of the different barium compounds depend on how well the compound dissolves in water or in the stomach contents. Barium has been found to potentially cause gastrointestinal disturbances and muscular weakness when people are exposed to it at levels above the EPA drinking water standards for relatively short periods of time. Some people who eat or drink amounts of barium above background levels found in food and water for a short period may experience vomiting, abdominal cramps, diarrhea, difficulties in breathing, increased or decreased blood pressure, numbness around the face, and muscle weakness. Barium compounds that do not dissolve well, such as barium sulfate, are not generally harmful. The EPA has determined that barium is not likely to be carcinogenic to humans following ingestion and that there is insufficient information to determine whether it will be carcinogenic to humans following inhalation exposure.")
        
        let photo8 = UIImage(named: "benzene.png")!
        let chem8 = ChemicalsListItem(text: "Benzene", photo: photo8, descrip: "Benzene is used mainly as a raw material for synthesizing chemicals such as styrene, phenol, and cyclohexane and for manufacturing dyes, detergents, explosives, rubber, plastics, and pharmaceuticals. It is found in trace amounts in cigarette smoke and drinking water, as a contaminant in some industrial solvents, and as a constituent of motor fuels, unleaded gasoline in particular. The Department of Health and Human Services has determined that benzene is a known human carcinogen. Most exposures to benzene occur by inhalation. Longer-term exposure to benzene may cause anemia, alterations to the immune system, and leukemia. Its odor threshold (1.5-5 ppm) generally provides adequate warning of acutely hazardous concentrations. Benzene has a sweet aromatic odor.")
        
        let photo9 = UIImage(named: "benzidine.png")!
        let chem9 = ChemicalsListItem(text: "Benzidine", photo: photo9, descrip: "Benzidine is a manufactured chemical that does not occur naturally. In the past, industry used large amounts of benzidine to produce dyes for cloth, paper, and leather. However, major U.S. dye companies no longer make benzidine-based dyes. If you live near a hazardous waste site, you could be exposed to benzidine by drinking contaminated water or by breathing or swallowing contaminated dust and soil. Benzidine can cause cancer. It is important to note that most of the workers, who were exposed for many years to levels much higher than the general population, did not develop cancer, even after such high exposures. When cancer does occur, most often it is cancer of the urinary bladder.")

        let photo10 = UIImage(named: "benzo(a)anthracene.png")!
        let chem10 = ChemicalsListItem(text: "Benzo(a)anthracene", photo: photo10, descrip: "Benzo(a)anthracene is one of a group of polycyclic aromatic hydrocarbons (PAHs). PAHs are a group of chemicals that are formed during the incomplete burning of coal, oil, gas, wood, garbage, or other organic substances, such as tobacco and charbroiled meat. There are more than 100 different PAHs. PAHs usually occur naturally, but they can be manufactured as individual compounds for research purposes. PAHs can be harmful to your health under some circumstances. Studies of people show that individuals exposed by breathing or skin contact for long periods to mixtures that contain PAHs and other compounds can develop cancer.")
        
        let photo11 = UIImage(named: "benzo(a)pyrene.png")!
        let chem11 = ChemicalsListItem(text: "Benzo(a)pyrene", photo: photo11, descrip: "Benzo(a)pyrene is one of a group of polycyclic aromatic hydrocarbons (PAHs). PAHs are a group of chemicals that are formed during the incomplete burning of coal, oil, gas, wood, garbage, or other organic substances, such as tobacco and charbroiled meat. There are more than 100 different PAHs. PAHs usually occur naturally, but they can be manufactured as individual compounds for research purposes. PAHs can be harmful to your health under some circumstances. Studies of people show that individuals exposed by breathing or skin contact for long periods to mixtures that contain PAHs and other compounds can develop cancer.")
        
        let photo12 = UIImage(named: "benzo(b)fluoranthene.png")!
        let chem12 = ChemicalsListItem(text: "Benzo(b)fluoranthene", photo: photo12, descrip: "Benzo(b)fluoranthene is one of a group of polycyclic aromatic hydrocarbons (PAHs). PAHs are a group of chemicals that are formed during the incomplete burning of coal, oil, gas, wood, garbage, or other organic substances, such as tobacco and charbroiled meat. There are more than 100 different PAHs. PAHs usually occur naturally, but they can be manufactured as individual compounds for research purposes. PAHs can be harmful to your health under some circumstances. Studies of people show that individuals exposed by breathing or skin contact for long periods to mixtures that contain PAHs and other compounds can develop cancer.")
        
        let photo13 = UIImage(named: "benzo(ghi)perylene.png")!
        let chem13 = ChemicalsListItem(text: "Benzo(ghi)perylene", photo: photo13, descrip: "Benzo(ghi)perylene is one of a group of polycyclic aromatic hydrocarbons (PAHs). PAHs are a group of chemicals that are formed during the incomplete burning of coal, oil, gas, wood, garbage, or other organic substances, such as tobacco and charbroiled meat. There are more than 100 different PAHs. PAHs usually occur naturally, but they can be manufactured as individual compounds for research purposes. PAHs can be harmful to your health under some circumstances. Studies of people show that individuals exposed by breathing or skin contact for long periods to mixtures that contain PAHs and other compounds can develop cancer.")
    
        let photo14 = UIImage(named: "benzo(k)fluoranthene.png")!
        let chem14 = ChemicalsListItem(text: "Benzo(k)fluoranthene", photo: photo14, descrip: "Benzo(k)flouranthene is one of a group of polycyclic aromatic hydrocarbons (PAHs). PAHs are a group of chemicals that are formed during the incomplete burning of coal, oil, gas, wood, garbage, or other organic substances, such as tobacco and charbroiled meat. There are more than 100 different PAHs. PAHs usually occur naturally, but they can be manufactured as individual compounds for research purposes. PAHs can be harmful to your health under some circumstances. Studies of people show that individuals exposed by breathing or skin contact for long periods to mixtures that contain PAHs and other compounds can develop cancer.")
        
        let photo15 = UIImage(named: "beryllium.png")!
        let chem15 = ChemicalsListItem(text: "Beryllium", photo: photo15, descrip: "Beryllium is an element that occurs naturally. It is present in a variety of materials, such as rocks, coal and oil, soil, and volcanic dust. Two kinds of mineral rocks, bertrandite and beryl, are mined commercially for the recovery of beryllium. Very pure gem-quality beryl is better known as either aquamarine (blue or blue-green) or emerald (green). People who live near hazardous landfill sites that contain high concentrations of beryllium may also be exposed to higher-than-normal levels of beryllium. Beryllium, as a chemical component, occurs naturally in tobacco and may be inhaled from cigarette smoke. Beryllium can enter your body if you breathe air, eat food, or drink water containing it. The U.S. Department of Health and Human Services and the International Agency for Research on Cancer have determined that beryllium and beryllium compounds are human carcinogens.")
        
        let photo16 = UIImage(named: "butanone.png")!
        let chem16 = ChemicalsListItem(text: "Butanone", photo: photo16, descrip: "2-Butanone is produced in large quantities. Nearly half of its use is in paints and other coatings because it will quickly evaporate into the air. It is also used in glues and as a cleaning agent. It is made by some trees and found in some fruits and vegetables in small amounts. It is also released to the air from car and truck exhausts. The known health effects to people from exposure to 2-butanone are irritation of the nose, throat, skin, and eyes. Two studies of workers exposed to 2-butanone and other chemicals did not find an increase in cancer.  No one has died from breathing 2-butanone alone.")
        
        let photo17 = UIImage(named: "cadmium.png")!
        let chem17 = ChemicalsListItem(text: "Cadmium", photo: photo17, descrip: "Most cadmium used in the United States is extracted as a byproduct during the production of other metals such as zinc, lead, or copper. Cadmium is also recovered from used batteries. Numerous studies have shown that acute inhalation exposure to cadmium can cause death in humans and animals. Lung cancer has been found in some studies of workers exposed to cadmium in the air and studies of rats that breathed in cadmium. Smoking greatly increases exposure to cadmium, as tobacco leaves naturally accumulate high amounts of cadmium. For nonsmokers the primary source of cadmium exposure is from the food supply. In general, leafy vegetables such as lettuce and spinach, potatoes and grains, peanuts, soybeans, and sunflower seeds contain high levels of cadmium. The EPA has determined that cadmium is a probable human carcinogen.")
        
        let photo18 = UIImage(named: "chlordane.png")!
        let chem18 = ChemicalsListItem(text: "Chlordane", photo: photo18, descrip: "Chlordane is a man-made chemical that was used as a pesticide in the United States from 1948 to 1988. It is sometimes referred to by the trade names Octachlor® and Velsicol 1068®. Before 1978, chlordane was used as a pesticide on agricultural crops, lawns, and gardens and as a fumigating agent. In 1988, when the EPA canceled chlordane's use for controlling termites, all approved use of chlordane in the United States stopped. Everyone in the United States has been exposed to low levels of chlordane. Today, people receive the highest exposure to chlordane from living in homes that were treated with chlordane for termites. Chlordane may be found in the air in these homes for many years after treatment. Most health effects in humans that may be linked to chlordane exposure are on the nervous system, the digestive system, and the liver. These effects were seen mostly in people who swallowed chlordane mixtures. It is not known whether chlordane will cause cancer in humans after long-term exposure. Studies of workers who made or used chlordane do not link exposure with cancer, but the information is not sufficient to know for sure.")
        
        let photo19 = UIImage(named: "chlorobenzene.png")!
        let chem19 = ChemicalsListItem(text: "Chlorobenzene", photo: photo19, descrip: "Chlorobenzene production in the United States has declined by more than 60% from its peak in 1960. It was used in the past to make other chemicals, such as phenol and DDT. Now chlorobenzene is used as a solvent for some pesticide formulations, to degrease automobile parts, and as a chemical intermediate to make several other chemicals. People that live near a waste site containing chlorobenzene could be exposed by drinking contaminated groundwater, breathing vapors released to the air, or getting contaminated soil on their skin. The EPA has determined that chlorobenzene is not classifiable as to human carcinogenicity based on inadequate evidence in both humans and animals.")
        
        let photo20 = UIImage(named: "chloroform.png")!
        let chem20 = ChemicalsListItem(text: "Chloroform", photo: photo20, descrip: "In the past, chloroform was used as an inhaled anesthetic during surgery, but it isn't used that way today. Today, chloroform is used to make other chemicals and can also be formed in small amounts when chlorine is added to water. Breathing air, eating food, or drinking water containing high levels of chloroform for long periods of time may damage your liver and kidneys. Large amounts of chloroform can cause sores when chloroform touches your skin.Rats and mice that ate food or drank water with chloroform developed cancer of the liver and kidneys. The Department of Health and Human Services (DHHS) has determined that chloroform may reasonably be anticipated to be a carcinogen. ")
        
        let photo21 = UIImage(named: "chlorophenol.png")!
        let chem21 = ChemicalsListItem(text: "Chlorophenol", photo: photo21, descrip: "Chlorophenols are primarily used as antiseptics, disinfectants, herbicides, pesticides, and wood preservatives. In addition to being produced commercially, small amounts of some chlorophenols may be produced when waste water or drinking water is disinfected with chlorine, if certain contaminants are present in the raw water. People are at greater risk of exposure if they live near industrial facilities that use or manufacture chlorophenols or waste sites that could be releasing it into the environment. Most released chlorophenols are found in surface water or have become adsorbed in soil near the release point. Children should be kept from coming in contact with water or dirt in an area that could be contaminated. Make sure they wash their hands frequently and before eating. Discourage your children from putting their hands in their mouths or other hand-to-mouth activity. The chlorophenols have a strong medicinal taste and odor; small amounts can be tasted in water. Very small amounts of chlorophenols can also make fish taste bad. The International Agency for Research on Cancer (IARC) has determined that the chlorophenols as a group, are possibly carcinogenic to man.")
        
        let photo22 = UIImage(named: "chromium.png")!
        let chem22 = ChemicalsListItem(text: "Chromium", photo: photo22, descrip: "Chromium is a naturally occurring element found in rocks, animals, plants, and soil. The most common forms are chromium(0), chromium(III), and chromium(VI). No taste or odor is associated with chromium compounds. The metal chromium, which is the chromium(0) form, is used for making steel. Chromium(III) is used for chrome plating, dyes and pigments, leather tanning, and wood preserving. Chromium can be found in air, soil, and water after release from the manufacture, use, and disposal of chromium-based products, and during the manufacturing process. Children should avoid playing in soils near uncontrolled hazardous waste sites where chromium may have been discarded. Chromium is a component of tobacco smoke. Avoid smoking in enclosed spaces like inside the home or car in order to limit exposure to children and other family members. Chromium(III) compounds do not appear to cause health problems following ingestion. Although chromium(III) is an essential nutrient, you should avoid excessive use of dietary supplements containing chromium.")

        let photo23 = UIImage(named: "chrysene.png")!
        let chem23 = ChemicalsListItem(text: "Chrysene", photo: photo23, descrip: "Chrysene is one of a group of polycyclic aromatic hydrocarbons (PAHs). PAHs are a group of chemicals that are formed during the incomplete burning of coal, oil, gas, wood, garbage, or other organic substances, such as tobacco and charbroiled meat. There are more than 100 different PAHs. PAHs usually occur naturally, but they can be manufactured as individual compounds for research purposes. PAHs can be harmful to your health under some circumstances. Studies of people show that individuals exposed by breathing or skin contact for long periods to mixtures that contain PAHs and other compounds can develop cancer.")
  
        let photo24 = UIImage(named: "copper.png")!
        let chem24 = ChemicalsListItem(text: "Copper", photo: photo24, descrip: "Copper is a metal that occurs naturally throughout the environment, in rocks, soil, water, and air. Copper is an essential element in plants and animals (including humans), which means it is necessary for us to live. Copper is used to make many different kinds of products like wire, plumbing pipes, and sheet metal. U.S. pennies made before 1982 are made of copper, while those made after 1982 are only coated with copper. Copper is also combined with other metals to make brass and bronze pipes and faucets. Copper compounds are commonly used in agriculture to treat plant diseases like mildew, for water treatment and, as preservatives for wood, leather, and fabrics. Copper is released into the environment by mining, farming, and manufacturing operations and through waste water releases into rivers and lakes. Copper is also released from natural sources, like volcanoes, windblown dusts, decaying vegetation, and forest fires. Breathing high levels of copper can cause irritation of your nose and throat. Ingesting high levels of copper can cause nausea, vomiting, and diarrhea. Very-high doses of copper can cause damage to your liver and kidneys, and can even cause death. The most likely place to be exposed to copper is through drinking water, especially if your water is corrosive and you have copper pipes in your house. The best way to lower the level of copper in your drinking water is to let the water run for at least 15 seconds first thing in the morning before drinking or using it. We do not know whether copper can cause cancer in humans. The EPA has determined that copper is not classifiable as to human carcinogenicity.")
        
        let photo25 = UIImage(named: "ddt.png")!
        let chem25 = ChemicalsListItem(text: "DDT", photo: photo25, descrip: "DDT (dichlorodiphenyltrichloroethane) is a pesticide once widely used to control insects in agriculture and insects that carry diseases such as malaria. Its use in the U.S. was banned in 1972 because of damage to wildlife, but is still used in some countries. DDE (dichlorodiphenyldichloroethylene) and DDD (dichlorodiphenyldichloroethane) are chemicals similar to DDT that contaminate commercial DDT preparations. DDE has no commercial use. DDD was also used to kill pests, but its use has also been banned. One form of DDD has been used medically to treat cancer of the adrenal gland. You may be exposed by breathing contaminated air or drinking contaminated water near waste sites and landfills that may contain higher levels of these chemicals, or by eating contaminated imported foods from countries that still allow the use of DDT to control pests. DDT affects the nervous system. People who accidentally swallowed large amounts of DDT became excitable and had tremors and seizures. These effects went away after the exposure stopped. A study in humans showed that women who had high amounts of a form of DDE in their breast milk were unable to breast feed their babies for as long as women who had little DDE in the breast milk. Another study in humans showed that women who had high amounts of DDE in breast milk had an increased chance of having premature babies. Studies in DDT-exposed workers did not show increases in cancer. The EPA determined that DDT, DDE, and DDD are probable human carcinogens.")

        let photo26 = UIImage(named: "dibenzo(a,h)anthracene.png")!
        let chem26 = ChemicalsListItem(text: "Dibenzo(a,h)anthracene", photo: photo26, descrip: "Dibenzo(a,h)anthracene is one of a group of polycyclic aromatic hydrocarbons (PAHs). PAHs are a group of chemicals that are formed during the incomplete burning of coal, oil, gas, wood, garbage, or other organic substances, such as tobacco and charbroiled meat. There are more than 100 different PAHs. PAHs usually occur naturally, but they can be manufactured as individual compounds for research purposes. PAHs can be harmful to your health under some circumstances. Studies of people show that individuals exposed by breathing or skin contact for long periods to mixtures that contain PAHs and other compounds can develop cancer.")
/*
        let photo27 = UIImage(named: "dichlorobenzene.png")!
        let chem27 = ChemicalsListItem(text: "Dichlorobenzene", photo: photo27, descrip: "Dichlorobenzenes do not occur naturally. There are three dichlorobenzene isomers- 1,2-dichlorobenzene, 1,3-dichlorobenzene, and 1,4-dichlorobenzene. 1,2-Dichlorobenzene is a colorless to pale yellow liquid used to make herbicides. 1,3- Dichlorobenzene is a colorless liquid used to make herbicides, insecticides, medicine, and dyes. 1,4-Dichlorobenzene enters the environment when it is used in mothballs and in toilet-deodorizer blocks. You may also be exposed to low levels of dichlorobenzenes in beef, pork, chicken, eggs, baked goods, soft drinks, butter, peanut butter, fruits, vegetables, and fish. Very little enters the environment from hazardous waste sites. Inhaling the vapor or dusts of 1,2-dichlorobenzene and 1,4- dichlorobenzene at very high concentrations could be very irritating to your eyes and nose and cause burning and tearing of the eyes, coughing, difficult breathing, and an upset stomach. Dizziness, headaches, and liver problems have also been observed in people exposed to very high levels of 1,4-dichlorobenzene. Both the International Agency for Research on Cancer (IARC) and the EPA concluded that 1,2- and 1,3- dichlorobenzene are not classifiable as to human carcinogenicity. The Department of Health and Human Services (DHHS) has determined that 1,4-dichlorobenzene may reasonably be anticipated to be a carcinogen.")
*/
        let photo28 = UIImage(named: "dichloroethene.png")!
        let chem28 = ChemicalsListItem(text: "Dichloroethene", photo: photo28, descrip: "1,1-Dichloroethene is an industrial chemical that is not found naturally in the environment. It is also called vinylidene chloride. 1,1-Dichloroethene is used to make certain plastics, such as flexible films like food wrap, and in packaging materials. It is also used to make flame retardant coatings for fiber and carpet backings, and in piping, coating for steel pipes, and in adhesive applications. Air near factories that make or use 1,1-dichloroethene and air near hazardous waste sites may contain low levels of it. The main effect from breathing high levels of 1,1-dichloroethene is on the central nervous system. Some people lost their breath and fainted after breathing high levels of the chemical. Breathing lower levels of 1,1-dichloroethene in air for a long time may damage your nervous system, liver, and lungs. Studies on workers who breathed 1,1-dichloroethene have not shown an increase in cancer. These studies, however, are not conclusive because of the small numbers of workers and the short time studied. The Environmental Protection Agency (EPA) has determined that 1,1-dichloroethene is a possible human carcinogen.")

        let photo29 = UIImage(named: "dieldrin.png")!
        let chem29 = ChemicalsListItem(text: "Dieldrin", photo: photo29, descrip: "Aldrin and dieldrin are the common names of two structurally similar compounds that were once used as insecticides. They are chemicals that are made in the laboratory and do not occur naturally in the environment.  The two chemicals are discussed together because aldrin readily changes into dieldrin once it enters either the environment or your body. From the 1950s until 1970, aldrin and dieldrin entered the environment when farmers used these compounds to kill pests on crops and when exterminators used them to kill termites. Aldrin and dieldrin are still present in the environment from these past uses. Symptoms of aldrin and dieldrin poisoning have been seen in people who were exposed to very large amounts of these pesticides during their manufacture. Most of these people experienced convulsions or other nervous system effects, and some had kidney damage. Health effects in people exposed to smaller amounts of aldrin or dieldrin occur because levels of the chemicals build up in the body over time. Exposure to moderate levels of aldrin or dieldrin for a long time causes headaches, dizziness, irritability, vomiting, or uncontrollable muscle movements. We do not know whether aldrin or dieldrin affects the ability of people to fight diseases, or causes birth defects or cancer in people.")
/*
        let photo30 = UIImage(named: "dimethylmercury.png")!
        let chem30 = ChemicalsListItem(text: "Dimethylmercury", photo: photo30, descrip: "description for chemical 3")
*/
        let photo31 = UIImage(named: "endosulfan.png")!
        let chem31 = ChemicalsListItem(text: "Endosulfan", photo: photo31, descrip: "Endosulfan is a restricted-use pesticide. It is particularly effective against aphids, fruit worms, beetles, leafhoppers, moth larvae, and white flies on a wide variety of crops. Endosulfan is applied to crops by aerial or ground-level foliar spray. The use of endosulfan is being restricted to certain crops and is scheduled to be canceled for all uses by 2016. Touching contaminated soil or fruits or plants that have been sprayed with endosulfan will result in a small amount entering the body through the skin. The main target of endosulfan toxicity is the nervous system. Exposure to high amounts of endosulfan induces hyperactivity and convulsions, regardless of the route of exposure. Severe poisoning may result in death. Studies of occupational and environmental exposure of humans have not provided conclusive evidence that endosulfan can cause cancer. Endosulfan did not cause cancer in animal studies. The Department of Health and Human Services (DHHS), the International Agency for Research on Cancer (IARC), and the EPA have not classified endosulfan as to its ability to cause cancer.")

        let photo32 = UIImage(named: "flouranthene.png")!
        let chem32 = ChemicalsListItem(text: "Flouranthene", photo: photo32, descrip: "Flouranthene is one of a group of polycyclic aromatic hydrocarbons (PAHs). PAHs are a group of chemicals that are formed during the incomplete burning of coal, oil, gas, wood, garbage, or other organic substances, such as tobacco and charbroiled meat. There are more than 100 different PAHs. PAHs usually occur naturally, but they can be manufactured as individual compounds for research purposes. PAHs can be harmful to your health under some circumstances. Studies of people show that individuals exposed by breathing or skin contact for long periods to mixtures that contain PAHs and other compounds can develop cancer.")

        let photo33 = UIImage(named: "heptachlor.png")!
        let chem33 = ChemicalsListItem(text: "Heptachlor", photo: photo33, descrip: "Heptachlor was used extensively in the past for killing insects in homes, buildings, and on food crops. These uses stopped in 1988. Currently it can only be used for fire ant control in underground power transformers. You may be exposed to heptachlor by drinking water, breathing air, or touching soil at waste sites that contain these substances, or by eating fish, dairy products, and fatty meats from animals exposed to heptachlor in their food. There is no reliable information on health effects in humans. Liver damage, excitability, and decreases in fertility have been observed in animals ingesting heptachlor. The effects are worse when the exposure levels were high or when exposure lasted many weeks. Lifetime exposure to heptachlor resulted in liver tumors in animals. The International Agency for Research on Cancer (IARC) and the EPA have classified heptachlor as a possible human carcinogen. EPA also considers heptachlor epoxide as a possible human carcinogen.")

        let photo34 = UIImage(named: "ideno(1,2,3-cd)pyrene.png")!
        let chem34 = ChemicalsListItem(text: "Indeno(1,2,3-cd)pyrene", photo: photo34, descrip: "Indeno(1,2,3-cd)pyrene is one of a group of polycyclic aromatic hydrocarbons (PAHs). PAHs are a group of chemicals that are formed during the incomplete burning of coal, oil, gas, wood, garbage, or other organic substances, such as tobacco and charbroiled meat. There are more than 100 different PAHs. PAHs usually occur naturally, but they can be manufactured as individual compounds for research purposes. PAHs can be harmful to your health under some circumstances. Studies of people show that individuals exposed by breathing or skin contact for long periods to mixtures that contain PAHs and other compounds can develop cancer.")
 
        let photo35 = UIImage(named: "lead.png")!
        let chem35 = ChemicalsListItem(text: "Lead", photo: photo35, descrip: "Lead has many different uses. It is used in the production of batteries, ammunition, metal products (solder and pipes), and devices to shield X-rays. Because of health concerns, lead from paints and ceramic products, caulking, and pipe solder has been dramatically reduced in recent years. The use of lead as an additive to gasoline was banned in 1996 in the United States. You might be exposed to lead by eating food or drinking water that contains lead. Water pipes in some older homes may contain lead solder. Lead can leach out into the water. Spending time in areas where lead-based paints have been used and are deteriorating can also expose you to lead. Deteriorating lead paint can contribute to lead dust. The effects of lead are the same whether it enters the body through breathing or swallowing. Lead can affect almost every organ and system in your body. The main target for lead toxicity is the nervous system, both in adults and children. Long-term exposure of adults can result in decreased performance in some tests that measure functions of the nervous system. It may also cause weakness in fingers, wrists, or ankles. Lead exposure also causes small increases in blood pressure, particularly in middle-aged and older people and can cause anemia. Exposure to high lead levels can severely damage the brain and kidneys in adults or children and ultimately cause death. We have no conclusive proof that lead causes cancer in humans, although The Department of Health and Human Services (DHHS) has determined that lead and lead compounds are reasonably anticipated to be human carcinogens and the EPA has determined that lead is a probable human carcinogen.")
        
        let photo36 = UIImage(named: "manganese.png")!
        let chem36 = ChemicalsListItem(text: "Manganese", photo: photo36, descrip: "Manganese is a naturally occurring metal that is found in many types of rocks. Manganese occurs naturally in most foods and may be added to some foods. Manganese is used principally in steel production to improve hardness, stiffness, and strength. It may also be used as an additive in gasoline to improve the octane rating of the gas. Manganese is an essential nutrient, and eating a small amount of it each day is important to stay healthy. The primary way you can be exposed to manganese is by eating food or manganese-containing nutritional supplements. Vegetarians, who consume foods rich in manganese such as grains, beans and nuts, as well as heavy tea drinkers, may have a higher intake of manganese than the average person. Certain occupations like welding or working in a factory where steel is made may increase your chances of being exposed to high levels of manganese. The most common health problems in workers exposed to high levels of manganese involve the nervous system. These health effects include behavioral changes and other nervous system effects, which include movements that may become slow and clumsy. Other less severe nervous system effects such as slowed hand movements have been observed in some workers exposed to lower concentrations in the work place. The EPA concluded that existing scientific information cannot determine whether or not excess manganese can cause cancer.")
        
        let photo37 = UIImage(named: "mercury.png")!
        let chem37 = ChemicalsListItem(text: "Mercury", photo: photo37, descrip: "Mercury is a naturally occurring metal which has several forms. Mercury combines with other elements, such as chlorine, sulfur, or oxygen, to form inorganic mercury compounds or 'salts,' which are usually white powders or crystals. The most common one, methylmercury, is produced mainly by microscopic organisms in the water and soil. More mercury in the environment can increase the amounts of methylmercury that these small organisms make. Metallic mercury is used to produce chlorine gas and caustic soda, and is also used in thermometers, dental fillings, and batteries. Mercury salts are sometimes used in skin lightening creams and as antiseptic creams and ointments. Inorganic mercury (metallic mercury and inorganic mercury compounds) enters the air from mining ore deposits, burning coal and waste, and from manufacturing plants. The nervous system is very sensitive to all forms of mercury. Methylmercury and metallic mercury vapors are more harmful than other forms, because more mercury in these forms reaches the brain. Exposure to high levels of metallic, inorganic, or organic mercury can permanently damage the brain, kidneys, and developing fetus. Effects on brain functioning may result in irritability, shyness, tremors, changes in vision or hearing, and memory problems. Short-term exposure to high levels of metallic mercury vapors may cause effects including lung damage, nausea, vomiting, diarrhea, increases in blood pressure or heart rate, skin rashes, and eye irritation. Short-term exposure to high levels of metallic mercury vapors may cause effects including lung damage, nausea, vomiting, diarrhea, increases in blood pressure or heart rate, skin rashes, and eye irritation. Carefully handle and dispose of products that contain mercury, such as thermometers or fluorescent light bulbs. Do not vacuum up spilled mercury, because it will vaporize and increase exposure. If a large amount of mercury has been spilled, contact your health department. Teach children not to play with shiny, silver liquids. The EPA has determined that mercuric chloride and methylmercury are possible human carcinogens.")
        
        let photo38 = UIImage(named: "methyl mercury.png")!
        let chem38 = ChemicalsListItem(text: "Methyl Mercury", photo: photo38, descrip: "Mercury is a naturally occurring metal which has several forms. Mercury combines with other elements, such as chlorine, sulfur, or oxygen, to form inorganic mercury compounds or 'salts,' which are usually white powders or crystals. The most common one, methylmercury, is produced mainly by microscopic organisms in the water and soil. More mercury in the environment can increase the amounts of methylmercury that these small organisms make. Metallic mercury is used to produce chlorine gas and caustic soda, and is also used in thermometers, dental fillings, and batteries. Mercury salts are sometimes used in skin lightening creams and as antiseptic creams and ointments. Inorganic mercury (metallic mercury and inorganic mercury compounds) enters the air from mining ore deposits, burning coal and waste, and from manufacturing plants. The nervous system is very sensitive to all forms of mercury. Methylmercury and metallic mercury vapors are more harmful than other forms, because more mercury in these forms reaches the brain. Exposure to high levels of metallic, inorganic, or organic mercury can permanently damage the brain, kidneys, and developing fetus. Effects on brain functioning may result in irritability, shyness, tremors, changes in vision or hearing, and memory problems. Short-term exposure to high levels of metallic mercury vapors may cause effects including lung damage, nausea, vomiting, diarrhea, increases in blood pressure or heart rate, skin rashes, and eye irritation. Short-term exposure to high levels of metallic mercury vapors may cause effects including lung damage, nausea, vomiting, diarrhea, increases in blood pressure or heart rate, skin rashes, and eye irritation. Carefully handle and dispose of products that contain mercury, such as thermometers or fluorescent light bulbs. Do not vacuum up spilled mercury, because it will vaporize and increase exposure. If a large amount of mercury has been spilled, contact your health department. Teach children not to play with shiny, silver liquids. The EPA has determined that mercuric chloride and methylmercury are possible human carcinogens.")
        
        let photo39 = UIImage(named: "methylene chloride.png")!
        let chem39 = ChemicalsListItem(text: "Methylene Chloride", photo: photo39, descrip: "Methylene chloride is a colorless liquid with a mild, sweet odor. Another name for it is dichloromethane. Methylene chloride does not occur naturally in the environment. Methylene chloride is used as an industrial solvent and as a paint stripper. It may also be found in some aerosol and pesticide products and is used in the manufacture of photographic film. The most likely way to be exposed to methylene chloride is by breathing contaminated air. Exposure to high levels of methylene chloride is likely if methylene chloride or a product containing it is used in a room with inadequate ventilation. If you breathe in large amounts of methylene chloride you may feel unsteady, dizzy, and have nausea and a tingling or numbness of your finger and toes. A person breathing smaller amounts of methylene chloride may become less attentive and less accurate in tasks requiring hand-eye coordination. Skin contact with methylene chloride causes burning and redness of the skin. We do not know if methylene chloride can cause cancer in humans. An increased cancer risk was seen in mice breathing large amounts of methylene chloride for a long time. The EPA has determined that methylene chloride is a probable cancer-causing agent in humans.")
        
        let photo40 = UIImage(named: "methylnapthalene.png")!
        let chem40 = ChemicalsListItem(text: "Methylnapthalene", photo: photo40, descrip: "1-Methylnaphthalene and 2-methylnaphthalene are naphthalene-related compounds. 1-Methylnaphthalene is a clear liquid and 2-methylnaphthalene is a solid; both can be smelled in air and in water at very low concentrations. 1-Methylnaphthalene and 2-methylnaphthalene are used to make other chemicals such as dyes and resins. Using or making moth repellents, coal tar products, dyes or inks could expose you to 3-methylnapthalene, as could breathing air contaminated from industrial discharges or smoke from burning wood, tobacco, or fossil fuels. 2-Methylnaphthalene is also used to make vitamin K. Exposure to naphthalene, 1-methylnaphthalene and 2-methylnaphthalene from eating foods or drinking beverages is unlikely. There are no studies of humans exposed to 1-methylnaphthalene or 2-methylnaphthalene.")
        
        let photo41 = UIImage(named: "napthalene.png")!
        let chem41 = ChemicalsListItem(text: "Napthalene", photo: photo41, descrip: "Naphthalene is a white solid that evaporates easily. Fuels such as petroleum and coal contain naphthalene. It is also called white tar, and tar camphor, and has been used in mothballs and moth flakes. Burning tobacco or wood produces naphthalene. It has a strong, but not unpleasant smell. Naphthalene enters the environment from industrial and domestic sources, and from accidental spills. Naphthalene can dissolve in water to a limited degree and may be present in drinking water from wells close to hazardous waste sites and landfills. Using or making moth repellents, coal tar products, dyes or inks could expose you to napthalene, as could breathing air contaminated from industrial discharges or smoke from burning wood, tobacco, or fossil fuels. Exposure to naphthalene from eating foods or drinking beverages is unlikely. Exposure to large amounts of naphthalene may damage or destroy some of your red blood cells. This could cause you to have too few red blood cells until your body replaces the destroyed cells. This condition is called hemolytic anemia. Some symptoms of hemolytic anemia are fatigue, lack of appetite, restlessness, and pale skin. Exposure to large amounts of naphthalene may also cause nausea, vomiting, diarrhea, blood in the urine, and a yellow color to the skin. There is no direct evidence in humans that naphthalene, 1-methylnaphthalene, or 2-methylnaphthalene cause cancer. However, cancer from naphthalene exposure has been seen in animal studies. The EPA determined that naphthalene is a possible human carcinogen.")
        
        let photo42 = UIImage(named: "nickel.png")!
        let chem42 = ChemicalsListItem(text: "Nickel", photo: photo42, descrip: "Nickel is a very abundant natural element that is found in all soil and is emitted from volcanoes. Nickel is also found in meteorites and on the ocean floor. Nickel can be combined with other metals, such as iron, copper, chromium, and zinc, to form alloys. These alloys are used to make coins, jewelry, and items such as valves and heat exchangers. Most nickel is used to make stainless steel. Nickel is released into the atmosphere by industries that make or use nickel, nickel alloys, or nickel compounds. It is also released into the atmosphere by oil-burning power plants, coal-burning power plants, and trash incinerators. You might be exposed by eating food containing nickel, which is the major source of exposure for most people, or by breathing air or smoking tobacco containing nickel. The most common harmful health effect of nickel in humans is an allergic reaction. People can become sensitive to nickel when jewelry or other things containing it are in direct contact with the skin for a long time. Once a person is sensitized to nickel, further contact with the metal may produce a reaction such as a skin rash at the site of contact. The skin rash may also occur at a site away from the site of contact. Some people who are sensitive to nickel have asthma attacks following exposure to nickel, or when they consume food or water containing nickel or breathe dust containing it. Cancers of the lung and nasal sinus have resulted when workers breathed dust containing high levels of nickel compounds while working in nickel refineries or nickel processing plants. The EPA has determined that nickel refinery dust and nickel subsulfide are human carcinogens.")
        
        let photo43 = UIImage(named: "nitrobenzene.png")!
        let chem43 = ChemicalsListItem(text: "Nitrobenzene", photo: photo43, descrip: "Nitrobenzene is an industrial chemical. It is produced in large quantities for use in industry. Most of the nitrobenzene produced in the United States is used to manufacture a chemical called aniline. Nitrobenzene is also used to produce lubricating oils such as those used in motors and machinery. A small amount of nitrobenzene is used in the manufacture of dyes, drugs, pesticides, and synthetic rubber. You might be exposed to nitrobenzene by living near a hazardous waste site where it has been disposed of. A small amount of nitrobenzene may cause mild irritation if it contacts the skin or eyes directly. Repeated exposures to a high concentration of nitrobenzene can result in methemoglobinemia, a condition in which the blood's ability to carry oxygen is reduced. If you have this condition, your skin may turn a bluish color and you may have nausea, vomiting, and shortness of breath. Effects such as headache, irritability, dizziness, weakness, and drowsiness may also occur. There is also some evidence that breathing high concentrations of nitrobenzene may damage the liver. The International Agency for Research on Cancer (IARC) has determined that nitrobenzene is possibly carcinogenic to humans.")
        
        let photo44 = UIImage(named: "pentachlorophenol.png")!
        let chem44 = ChemicalsListItem(text: "Pentachlorophenol", photo: photo44, descrip: "Pentachlorophenol is a manufactured chemical that does not occur naturally. Pentachlorophenol was widely used as a pesticide and wood preservative. Since 1984, the purchase and use of pentachlorophenol has been restricted to certified applicators. It is no longer available to the general public. It is still used industrially as a wood preservative for utility poles, railroad ties, and wharf pilings. People who work or live near a wood treatment facility or in the production of utility poles, railroad ties, or wharf pilings may be exposed to pentachlorophenol in the air or by coming in contact with the treated wood. If you live near utility poles and railroad tracks, you should prevent your children from playing, climbing, or sitting on them especially in the hot summer months. People living near hazardous waste sites may also be exposed to higher than usual levels of pentachlorophenol. Studies in workers show that exposure to high levels of pentachlorophenol can cause the cells in the body to produce excess heat. When this occurs, a person may experience a very high fever, profuse sweating, and difficulty breathing. The body temperature can increase to dangerous levels, causing injury to various organs and tissues, and even death. Liver effects and damage to the immune system have also been observed in humans exposed to high levels of pentachlorophenol for a long time. The EPA has determined that pentachlorophenol is a probable human carcinogen and the International Agency for Cancer Research (IARC) considers it possibly carcinogenic to humans.")

        let photo45 = UIImage(named: "phenanthrene.png")!
        let chem45 = ChemicalsListItem(text: "Phenanthrene", photo: photo45, descrip: "Phenanthrene is one of a group of polycyclic aromatic hydrocarbons (PAHs). PAHs are a group of chemicals that are formed during the incomplete burning of coal, oil, gas, wood, garbage, or other organic substances, such as tobacco and charbroiled meat. There are more than 100 different PAHs. PAHs usually occur naturally, but they can be manufactured as individual compounds for research purposes. PAHs can be harmful to your health under some circumstances. Studies of people show that individuals exposed by breathing or skin contact for long periods to mixtures that contain PAHs and other compounds can develop cancer.")

        let photo46 = UIImage(named: "phenol.png")!
        let chem46 = ChemicalsListItem(text: "Phenol", photo: photo46, descrip: "You can taste and smell phenol at levels lower than those that are associated with harmful effects. Phenol evaporates more slowly than water, and a moderate amount can form a solution with water. Phenol is used primarily in the production of phenolic resins and in the manufacture of nylon and other synthetic fibers. It is also used in slimicides (chemicals that kill bacteria and fungi in slimes), as a disinfectant and antiseptic, and in medicinal preparations such as mouthwash and sore throat lozenges. You may be exposed to phenol if you live near landfills or hazardous waste sites that contain phenol or near facilities manufacturing phenol, or to very low levels in your home because it is found in a number of consumer products, including mouthwashes and throat lozenges. Low levels of phenol are also found in some foods, including smoked summer sausage, fried chicken, mountain cheese, and some species of fish. Smoking or inhaling second hand smoke will also expose you to phenol. Short-term exposure to phenol in the air can cause respiratory irritation, headaches, and burning eyes. People who had skin exposure to high amounts of phenol had skin burns, liver damage, dark urine, irregular heart beat, and some died. Ingestion of high concentrations of phenol has resulted in internal burns and death. The International Agency for Research on Cancer (IARC) and the EPA have determined that phenol is not classifiable as to its carcinogenicity to humans.")

        let photo47 = UIImage(named: "pyrene.png")!
        let chem47 = ChemicalsListItem(text: "Pyrene", photo: photo47, descrip: "Pyrene is one of a group of polycyclic aromatic hydrocarbons (PAHs). PAHs are a group of chemicals that are formed during the incomplete burning of coal, oil, gas, wood, garbage, or other organic substances, such as tobacco and charbroiled meat. There are more than 100 different PAHs. PAHs usually occur naturally, but they can be manufactured as individual compounds for research purposes. PAHs can be harmful to your health under some circumstances. Studies of people show that individuals exposed by breathing or skin contact for long periods to mixtures that contain PAHs and other compounds can develop cancer.")

        let photo48 = UIImage(named: "selenium.png")!
        let chem48 = ChemicalsListItem(text: "Selenium", photo: photo48, descrip: "Selenium is a naturally occurring mineral element that is distributed widely in nature in most rocks and soils. Most processed selenium is used in the electronics industry, but it is also used: as a nutritional supplement; in the glass industry; as a component of pigments in plastics, paints, enamels, inks, and rubber; in the preparation of pharmaceuticals; as a nutritional feed additive for poultry and livestock; in pesticide formulations; in rubber production; as an ingredient in antidandruff shampoos; and as a constituent of fungicides. The general population is exposed to very low levels of selenium in air, food, and water. The majority of the daily intake comes from food. People living in the vicinity of hazardous waste sites or coal burning plants may be exposed to higher levels of selenium. Selenium has both beneficial and harmful effects. Low doses of selenium are needed to maintain good health. However, exposure to high levels can cause adverse health effects. Short-term oral exposure to high concentrations of selenium may cause nausea, vomiting, and diarrhea. Chronic oral exposure to high concentrations of selenium compounds can produce hair loss, nail brittleness, and neurological abnormalities (such as numbness and other odd sensations in the extremities). Brief exposures to high levels of elemental selenium or selenium dioxide in air can result in respiratory tract irritation, bronchitis, difficulty breathing, and stomach pains. Longer-term exposure to either of these air-borne forms can cause respiratory irritation, bronchial spasms, and coughing. Studies of laboratory animals and people show that most selenium compounds probably do not cause cancer. In fact, studies in humans suggest that lower-than-normal selenium levels in the diet might increase the risk of cancer.")
        
        let photo49 = UIImage(named: "silver.png")!
        let chem49 = ChemicalsListItem(text: "Silver", photo: photo49, descrip: "Silver is used to make jewelry, silverware, electronic equipment, and dental fillings. It is also used to make photographs, in brazing alloys and solders, to disinfect drinking water and water in swimming pools, and as an antibacterial agent. Silver has also been used in lozenges and chewing gum to help people stop smoking. Silver may be released into the air and water through natural processes such as the weathering of rocks. Human activities such as the processing of ores, cement manufacture, and the burning of fossil fuel may also release silver into the air. Exposure to high levels of silver for a long period of time may result in a condition called arygria, a blue-gray discoloration of the skin and other body tissues. Argyria is a permanent effect, but it appears to be a cosmetic problem that may not be otherwise harmful to health. Exposure to high levels of silver in the air has resulted in breathing problems, lung and throat irritation, and stomach pains. Skin contact with silver can cause mild allergic reactions such as rash, swelling, and inflammation in some people. No studies are available on whether silver may cause cancer in people. The only available animal studies showed both positive and negative results when silver was implanted under the skin.")
        
        let photo50 = UIImage(named: "tetrachloroethene.png")!
        let chem50 = ChemicalsListItem(text: "Tetrachloroethene", photo: photo50, descrip: "Tetrachloroethylene is used as a dry cleaning agent and metal degreasing solvent. When you bring clothes from the dry cleaners, they will release small amounts of tetrachloroethylene into the air. People residing near contaminated sites or dry cleaning locations may be exposed to higher levels than the general population. Breathing high levels of tetrachloroethylene for a brief period may cause dizziness or drowsiness, headache, and incoordination; higher levels may cause unconsciousness and even death. Exposure for longer periods to low levels of tetrachloroethylene may cause changes in mood, memory, attention, reaction time, and vision. Studies in humans suggest that exposure to tetrachloroethylene might lead to a higher risk of getting bladder cancer, multiple myeloma, or non-Hodgkin's lymphoma, but the evidence is not very strong.")
        
        let photo51 = UIImage(named: "thallium.png")!
        let chem51 = ChemicalsListItem(text: "Thallium", photo: photo51, descrip: "Thallium is used mostly in manufacturing electronic devices, switches, and closures, primarily for the semiconductor industry. It also has limited use in the manufacture of special glass and for certain medical procedures. In the past, thallium was obtained as a by-product from smelting other metals; however, it has not been produced in the United States since 1984. Currently, all the thallium is obtained from imports and from thallium reserves. It's absorbed by plants and enters the food chain; it builds up in fish and shellfish. Eating food contaminated with thallium may be a major source of exposure for most people. Living near hazardous waste sites containing thallium may result in higher than normal exposures. No studies are available in people or animals on the carcinogenic effects of breathing, ingesting, or touching thallium.")
        
        let photo52 = UIImage(named: "toluene.png")!
        let chem52 = ChemicalsListItem(text: "Toluene", photo: photo52, descrip: "Toluene occurs naturally in crude oil and in the resin of a tree called 'quina' or 'tolu'. It is produced in the process of making gasoline and other fuels from crude oil and in making coke from coal. Toluene is used in making paints, paint thinners, fingernail polish, lacquers, adhesives, and rubber and in some printing and leather tanning processes. Toluene is also used in the manufacture of other chemicals, nylon, and plastics, or added to gasoline along with benzene and xylene to improve octane ratings. When toluene-containing products are placed in landfills or waste disposal sites, toluene can enter the soil or water near the waste site. Toluene may affect the nervous system. Low to moderate levels can cause tiredness, confusion, weakness, drunken-type actions, memory loss, nausea, and loss of appetite. These symptoms usually disappear when exposure stops. Long-term daily inhalation exposure to toluene in the workplace may cause some hearing and color vision loss. Repeatedly breathing toluene from glue or paint thinners may permanently damage the brain. The EPA determined there is inadequate information to assess the carcinogenic potential of toluene.")
        
        let photo53 = UIImage(named: "trichlorobenzene.png")!
        let chem53 = ChemicalsListItem(text: "Trichlorobenzene", photo: photo53, descrip: "Trichlorobenzenes have primarily been used as solvents and chemical intermediates to produce other compounds. 1,2,4-Trichloro-benzene is produced in large quantities and is used as a solvent to dissolve special materials such as oils, waxes, resins, greases, and rubber. It is also frequently used to produce dyes and textiles. Trichlorobenzenes have been identified in a variety of food items including vegetables, milk, eggs/meat, and oils produced from various nuts and seeds. High levels of trichlorobenzenes are often detected in fish or other species living in contaminated waters because trichlorobenzenes can accumulate in fatty tissues. There is virtually no information regarding health effects of trichlorobenzenes in humans. However, based on results from studies in animals, it is reasonable to predict that humans exposed to high amounts of trichlorobenzenes may develop liver problems. Mice given 1,2,4-trichlorobenzene in the food for 2 years developed cancer of the liver. The EPA has stated that 1,2,4-trichlorobenzene is not classifiable as to human carcinogenicity. However, this was based on studies conducted prior to 1990; newer information has not been evaluated.")
        
        let photo54 = UIImage(named: "trichloroethane.png")!
        let chem54 = ChemicalsListItem(text: "Trichloroethane", photo: photo54, descrip: "1,1,1-Trichloroethane is a synthetic chemical that does not occur naturally in the environment. No 1,1,1-trichloroethane is supposed to be manufactured for domestic use in the United States after January 1, 2002 because it affects the ozone layer. 1,1,1-Trichloroethane had many industrial and household uses, including use as a solvent to dissolve other substances, such as glues and paints; to remove oil or grease from manufactured metal parts; and as an ingredient of household products such as spot cleaners, glues, and aerosol sprays. Most of the 1,1,1-trichloroethane released into the environment enters the air, where it lasts for about 6 years. Because 1,1,1 trichloroethane was used so frequently in home and office products, you are likely to be exposed to higher levels indoors than outdoors or near hazardous waste sites. If you breathe air containing high levels of 1,1,1-trichloroethane for a short time, you may become dizzy and lightheaded and possibly lose your coordination. These effects rapidly disappear after you stop breathing contaminated air. If you breathe in much higher levels, you may become unconscious, your blood pressure may decrease, and your heart may stop beating. Available information does not indicate that 1,1,1-trichloroethane causes cancer.")
        
        let photo55 = UIImage(named: "trichloroethene.png")!
        let chem55 = ChemicalsListItem(text: "Trichloroethene", photo: photo55, descrip: "Trichloroethylene is used as a solvent for cleaning metal parts and as a chemical that is used to make other chemicals. Trichloroethylene was once used as an anesthetic for surgery. Workers at facilities using this substance for metal degreasing are exposed to higher levels of trichloroethylene. If you live near such a facility or near a hazardous waste site containing trichloroethylene, you may also have higher exposure to this substance. Exposure to moderate amounts of trichloroethylene may cause headaches, dizziness, and sleepiness; large amounts may cause coma and even death. Eating or breathing high levels of trichloroethylene may damage some of the nerves in the face. Exposure to high levels can also result in changes in the rhythm of the heartbeat, liver damage, and evidence of kidney damage. Skin contact with concentrated solutions of trichloroethylene can cause skin rashes. There is some evidence exposure to trichloroethylene in the work place may cause scleroderma (a systemic autoimmune disease) in some people. The IARC and the EPA determined that there is convincing evidence that trichloroethylene exposure can cause kidney cancer.")
        
        let photo56 = UIImage(named: "vanadium.png")!
        let chem56 = ChemicalsListItem(text: "Vanadium", photo: photo56, descrip: "Vanadium is an element that occurs in nature. It usually combines with other elements such as oxygen, sodium, sulfur, or chloride. Vanadium and vanadium compounds can be found in the earth's crust and in rocks, some iron ores, and crude petroleum deposits. Vanadium is used in producing rust-resistant, spring, and high-speed tool steels. Vanadium mainly enters the environment from natural sources and from the burning of fuel oils. Vanadium is also a component of tobacco smoke. Avoid smoking in enclosed spaces like inside the home or car in order to limit exposure to children and other family members. Exposure to high levels of vanadium pentoxide in air can result in lung damage. The International Agency for Research on Cancer (IARC) has classified vanadium pentoxide as possibly carcinogenic to humans based on evidence of lung cancer in exposed mice.")
        
        let photo57 = UIImage(named: "vinyl chloride.png")!
        let chem57 = ChemicalsListItem(text: "Vinyl Chloride", photo: photo57, descrip: "Vinyl chloride is a colorless gas. It burns easily and it is not stable at high temperatures. It has a mild, sweet odor. It is a manufactured substance that does not occur naturally. Vinyl chloride is used to make polyvinyl chloride (PVC). PVC is used to make a variety of plastic products, including pipes, wire and cable coatings, and packaging materials. Some people who work with vinyl chloride have nerve damage and develop immune reactions, or have problems with the blood flow in their hands. Breathing high levels of vinyl chloride can cause you to feel dizzy or sleepy. Breathing very high levels can cause you to pass out, and breathing extremely high levels can cause death. The U.S. Department of Health and Human Services has determined that vinyl chloride is a known carcinogen. Studies in workers who have breathed vinyl chloride over many years showed an increased risk of liver, brain, lung cancer, and some cancers of the blood have also been observed in workers. Animal studies also suggest that infants and young children might be more susceptible than adults to vinyl chloride-induced cancer.")
        
        let photo58 = UIImage(named: "zinc.png")!
        let chem58 = ChemicalsListItem(text: "Zinc", photo: photo58, descrip: "Zinc is a naturally occurring element. Some is released into the environment by natural processes, but most comes from human activities like mining, steel production, coal burning, and burning of waste. Exposure to high levels of zinc occurs mostly from eating food, drinking water, or breathing workplace air that is contaminated. Zinc is an essential element in our diet; low levels of zinc are essential for maintaining good health. Exposure to large amounts of zinc can be harmful. It can cause stomach cramps, anemia, and changes in cholesterol levels. Harmful effects generally begin at levels 10-15 times higher than the amount needed for good health. Based on incomplete information from human and animal studies, the EPA has determined that zinc is not classifiable as to its human carcinogenicity.")

        
        chemicalsList += [chem1, chem2, chem3, chem4, chem5, chem6, chem7, chem8, chem9, chem10, chem11, chem12, chem13, chem14, chem15, chem16, chem17, chem18, chem19, chem20, chem21, chem22, chem23, chem24, chem25, chem26,/* chem27,*/ chem28, chem29, /*chem30, */chem31, chem32, chem33, chem34, chem35, chem36, chem37, chem38, chem39, chem40, chem41, chem42, chem43, chem44, chem45, chem46, chem47, chem48, chem49, chem50, chem51, chem52, chem53, chem54, chem55, chem56, chem57, chem58]
        
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }

    // MARK: - Table view data source

    override func numberOfSectionsInTableView(tableView: UITableView) -> Int {
        return 1
    }

    override func tableView(tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return chemicalsList.count
    }
    
    
    override func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
        let cellIdentifier = "ChemicalsTableViewCell"
        let cell = tableView.dequeueReusableCellWithIdentifier(cellIdentifier, forIndexPath: indexPath) as! ChemicalsTableViewCell
        let chemical = chemicalsList[indexPath.row]
        
        cell.chemLabel.text = chemical.text
        
        return cell
    }

    /*
    // Override to support conditional editing of the table view.
    override func tableView(tableView: UITableView, canEditRowAtIndexPath indexPath: NSIndexPath) -> Bool {
        // Return NO if you do not want the specified item to be editable.
        return true
    }
    */

    /*
    // Override to support editing the table view.
    override func tableView(tableView: UITableView, commitEditingStyle editingStyle: UITableViewCellEditingStyle, forRowAtIndexPath indexPath: NSIndexPath) {
        if editingStyle == .Delete {
            // Delete the row from the data source
            tableView.deleteRowsAtIndexPaths([indexPath], withRowAnimation: .Fade)
        } else if editingStyle == .Insert {
            // Create a new instance of the appropriate class, insert it into the array, and add a new row to the table view
        }    
    }
    */

    /*
    // Override to support rearranging the table view.
    override func tableView(tableView: UITableView, moveRowAtIndexPath fromIndexPath: NSIndexPath, toIndexPath: NSIndexPath) {

    }
    */

    /*
    // Override to support conditional rearranging of the table view.
    override func tableView(tableView: UITableView, canMoveRowAtIndexPath indexPath: NSIndexPath) -> Bool {
        // Return NO if you do not want the item to be re-orderable.
        return true
    }
    */

    /*
    // MARK: - Navigation

    // In a storyboard-based application, you will often want to do a little preparation before navigation
    override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?) {
        // Get the new view controller using [segue destinationViewController].
        // Pass the selected object to the new view controller.
    }
    */
    
    override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?) {
        if segue.identifier == "showChemicalDetail" {
            let chemicalDetailsViewController = segue.destinationViewController as!
            ChemicalDetailsViewController
            if let selectedChemCell = sender as? ChemicalsTableViewCell {
                let indexPath = tableView.indexPathForCell(selectedChemCell)
                let selectedChemical = chemicalsList[indexPath!.row]
                chemicalDetailsViewController.currentChemical = selectedChemical
                
            }
            
        }
    }
    
    @IBAction func unwindToHome(segue:UIStoryboardSegue) {
        
    }

}
